config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :powers, only: [:index, :show]
  resources :heroines, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heroine.rb
class Heroine < ApplicationRecord
  belongs_to :power

  validates :super_name, uniqueness: true
  validates :name, presence: true

  def self.search(search)
    if search
      power = Power.find_by(name: search)
      if power
        self.where(power_id: power)
      else
        Herione.all
      end
    else
      Heroine.all
    end
  end
end

app/models/power.rb
class Power < ApplicationRecord
  has_many :heroines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/heroines_controller.rb
class HeroinesController < ApplicationController
  def index
    @heroines = Heroine.all
    @heroines = Heroine.search(params[:search])
  end

  def show
    @heroine = Heroine.find_by(id: params[:id])
    @power = @heroine.power
  end

  def new
    @heroine = Heroine.new
  end

  def create
    @heroine = Heroine.new(heroine_params)
    if @heroine.valid?
      @heroine.save
      redirect_to heroines_path
    else
      render 'new'
    end
  end

  private

  def heroine_params
    params.require(:heroine).permit(:name, :super_name, :power_id, :search)
  end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  def index
    @powers = Power.all
  end

  def show
    @power = Power.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/heroines/index.html.erb
<h2>All Heroines</h2>

<ul>
  <% @heroines.each do |heroine| %>
    <li>
      <%= link_to heroine.super_name, heroine_path(heroine) %>
    </li>
    <br>

  <% end %>
</ul>

<h4>Search by Heroine's Super Powers</h4>
<%= form_tag(heroines_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/heroines/new.html.erb
<h1>Add a New Heroine</h1>

<%= form_for(@heroine) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :super_name %>
  <%= f.text_field :super_name %>
  <%= f.collection_select :power_id, Power.all, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/heroines/show.html.erb
<h1>Heroine Name: <%= @heroine.name %></h1>

<h2>Heroine Super Name: <%= @heroine.super_name %></h2>

<h2>Heroine Super Power: <%= link_to @heroine.power.name, power_path(@power.id) %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heroines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/powers/index.html.erb
<h2>All Superpowers</h2>

<ul>
  <% @powers.each do |power| %>
    <li>
      <%= link_to power.name, power_path(power) %>
      <br>
      Description: <%= power.description %>
    </li>
    <br>
  <% end %>
</ul>

app/views/powers/show.html.erb
<h1>Superpower:</h1>
<h2>Power Name: <%= @power.name %></h2>
<h2>Power Description: <%= @power.description %></h2>